import Head from "next/head";
import styles from "../styles/home.module.css";
import CardHolder from "../components/cardHolder.jsx";
import LineTitle from "../components/lineTitle.jsx";
import ContactMe from "../components/contactMe.jsx";
import BackgroundCode from "../public/background_code.png";
import TextOverImage from "../components/textOverImage.jsx";
import {projectsCarouselData, skillCarouselData, contactLinks} from "../data";
import Link from "next/link";
import pfp from "../public/profile_picture.png";

import Landing from "../components/landing.jsx";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>NickSkelin</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				{/* <TextOverImage
					imageSource={BackgroundCode}
					alt="Image"
					title="Hey, I'm Nick!"
					description="I design and develop websites!"
				/>
				<div className={styles.about}>
					<LineTitle title="About me" />
					<p className={styles.aboutText}>
						Im a graduate of BCIT&apos;s Computer information technology diploma program and specialize in full-stack
						web development. I have a years worth of experience in web development and can even design your website to
						suit your needs. If you want to see the specifics of my skill-set or previous works, just check below!
					</p>
				</div> */}
				<Landing imageSrc={pfp} title={"Hey, im Nick!"} subtitle={"I develop websites & stuff"}></Landing>

				<CardHolder title="Skills" cards={skillCarouselData.cards} style={{direction: "left", color: "#2274a5"}} />
				<CardHolder
					title="Recent works"
					cards={projectsCarouselData.cards}
					style={{direction: "right", color: "#eb6534"}}
				/>
				<ContactMe links={contactLinks} />
			</main>

			<footer className={styles.footer}>
				<p>
					Icons by{" "}
					<a href="https://icons8.com/">
						<b>
							<u>Icons8.com</u>
						</b>
					</a>
					. Click{" "}
					<Link href={"/license"} passHref>
						<b>
							<u>here</u>
						</b>{" "}
					</Link>
					for open source software licensing.
				</p>
			</footer>
		</div>
	);
}
